fix: Use standard runner instead

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -16,199 +16,208 @@ concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
 jobs:
-  changed_files:
-    if: ${{ github.event.pull_request.draft == false }}
-    runs-on: ubuntu-latest
-    name: Test changed-files
-    outputs:
-      changed-rust-files: ${{ steps.changed-files-yaml.outputs.code_any_changed }}
-      changed-lockfile-files: ${{ steps.changed-files-yaml.outputs.lockfile_any_changed }}
-      changed-docker-files: ${{ steps.changed-files-yaml.outputs.docker_any_changed }}
-      changed-tests-files: ${{ steps.changed-files-yaml.outputs.tests_any_changed }}
-    steps:
-      # Checkout the repository
-      - name: Checkout Code
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
-      - name: Get changed files
-        id: changed-files-yaml
-        uses: tj-actions/changed-files@d6e91a2266cdb9d62096cebf1e8546899c6aa18f  # v45.0.6
-        with:
-          files_yaml: |
-            code:
-              - '**/*.rs'
-              - 'rustfmt.toml'
-              - 'rust-toolchain.toml'
-            lockfile:
-              - 'Cargo.lock'
-              - 'Cargo.toml'
-            docker:
-              - 'Dockerfile.development'
-              - 'Dockerfile.production'
-              - 'docker-compose.yml'
-              - 'Cargo.lock'
-              - 'Cargo.toml'
-            tests:
-              - '**/*.rs'
-              - 'tests/**/*.json'
-  ci:
-    if: ${{ github.event.pull_request.draft == false && always() }}
-    permissions:
-      contents: none
-    name: CI
-    needs: [test, msrv, rustfmt, clippy]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Failed
-        run: exit 1
-        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
-  msrv:
-    if: |
-      ${{ github.event.pull_request.draft == false && github.event_name != 'push' && ( needs.changed_files.outputs.changed-rust-files == 'true' || needs.changed_files.outputs.changed-lockfile-files == 'true') }}
-    runs-on: ubuntu-latest
-    needs: changed_files
-    steps:
-      # Checkout the repository
-      - name: Checkout Code
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
-      - name: Prepare
-        id: init
-        uses: ./.github/actions/prepare
+  # changed_files:
+  #   if: ${{ github.event.pull_request.draft == false }}
+  #   runs-on: ubuntu-latest
+  #   name: Test changed-files
+  #   outputs:
+  #     changed-rust-files: ${{ steps.changed-files-yaml.outputs.code_any_changed }}
+  #     changed-lockfile-files: ${{ steps.changed-files-yaml.outputs.lockfile_any_changed }}
+  #     changed-docker-files: ${{ steps.changed-files-yaml.outputs.docker_any_changed }}
+  #     changed-tests-files: ${{ steps.changed-files-yaml.outputs.tests_any_changed }}
+  #   steps:
+  #  # Checkout the repository
+  #     - name: Checkout Code
+  #       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
+  #     - name: Get changed files
+  #       id: changed-files-yaml
+  #       uses: tj-actions/changed-files@d6e91a2266cdb9d62096cebf1e8546899c6aa18f  # v45.0.6
+  #       with:
+  #         files_yaml: |
+  #           code:
+  #             - '**/*.rs'
+  #             - 'rustfmt.toml'
+  #             - 'rust-toolchain.toml'
+  #           lockfile:
+  #             - 'Cargo.lock'
+  #             - 'Cargo.toml'
+  #           docker:
+  #             - 'Dockerfile.development'
+  #             - 'Dockerfile.production'
+  #             - 'docker-compose.yml'
+  #             - 'Cargo.lock'
+  #             - 'Cargo.toml'
+  #           tests:
+  #             - '**/*.rs'
+  #             - 'tests/**/*.json'
+  # ci:
+  #   if: ${{ github.event.pull_request.draft == false && always() }}
+  #   permissions:
+  #     contents: none
+  #   name: CI
+  #   needs: [test, msrv, rustfmt, clippy]
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Failed
+  #       run: exit 1
+  #       if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
+  # msrv:
+  #   if: |
+  #     ${{ github.event.pull_request.draft == false && github.event_name != 'push' && ( needs.changed_files.outputs.changed-rust-files == 'true' || needs.changed_files.outputs.changed-lockfile-files == 'true') }}
+  #   runs-on: ubuntu-latest
+  #   needs: changed_files
+  #   timeout-minutes: 10
+  #   steps:
+  #  # Checkout the repository
+  #     - name: Checkout Code
+  #       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
+  #     - name: Prepare
+  #       id: init
+  #       uses: ./.github/actions/prepare
 
-      # Get the output of the prepare composite action
-      - name: Get cache-hit output
-        run: 'echo "Cache hit >>>>>: ${{ steps.init.outputs.cache-hit }}"'
-      - name: Install cargo hack
-        uses: taiki-e/install-action@cargo-hack
+  #  # Get the output of the prepare composite action
+  #     - name: Get cache-hit output
+  #       run: 'echo "Cache hit >>>>>: ${{ steps.init.outputs.cache-hit }}"'
+  #     - name: Install cargo hack
+  #       uses: taiki-e/install-action@cargo-hack
 
-      # Check the minimum supported Rust version
-      - name: Default features
-        run: cargo hack check --feature-powerset --locked --rust-version --all-targets
-  rustfmt:
-    if: |
-      ${{ github.event.pull_request.draft == false && github.event_name != 'push' && needs.changed_files.outputs.changed-rust-files == 'true' }}
-    needs: changed_files
-    runs-on: ubuntu-latest
-    steps:
-      # Checkout the repository
-      - name: Checkout Code
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
-      - name: Prepare
-        id: init
-        uses: ./.github/actions/prepare
+  #  # Check the minimum supported Rust version
+  #     - name: Default features
+  #       run: cargo hack check --feature-powerset --locked --rust-version --all-targets
+  # rustfmt:
+  #   if: |
+  #     ${{ github.event.pull_request.draft == false && github.event_name != 'push' && needs.changed_files.outputs.changed-rust-files == 'true' }}
+  #   needs: changed_files
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 10
+  #   steps:
+  #  # Checkout the repository
+  #     - name: Checkout Code
+  #       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
+  #     - name: Prepare
+  #       id: init
+  #       uses: ./.github/actions/prepare
 
-      # Get the output of the prepare composite action
-      - name: Get cache-hit output
-        run: 'echo "Cache hit >>>>>: ${{ steps.init.outputs.cache-hit }}"'
+  #  # Get the output of the prepare composite action
+  #     - name: Get cache-hit output
+  #       run: 'echo "Cache hit >>>>>: ${{ steps.init.outputs.cache-hit }}"'
 
-      # Check the formatting of the code
-      - name: Check formatting
-        run: cargo fmt --all -- --check
+  #  # Check the formatting of the code
+  #     - name: Check formatting
+  #       run: cargo fmt --all -- --check
 
-  # lint checks
-  clippy:
-    if: |
-      ${{ github.event.pull_request.draft == false && github.event_name != 'push' && needs.changed_files.outputs.changed-rust-files == 'true' }}
-    needs: changed_files
-    runs-on: ubuntu-latest
-    steps:
-      # Checkout the repository
-      - name: Checkout Code
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
-      - name: Prepare
-        id: init
-        uses: ./.github/actions/prepare
+  #  # lint checks
+  # clippy:
+  #   if: |
+  #     ${{ github.event.pull_request.draft == false && github.event_name != 'push' && needs.changed_files.outputs.changed-rust-files == 'true' }}
+  #   needs: changed_files
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 10
+  #   steps:
+  #  # Checkout the repository
+  #     - name: Checkout Code
+  #       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
+  #     - name: Prepare
+  #       id: init
+  #       uses: ./.github/actions/prepare
 
-      # Get the output of the prepare composite action
-      - name: Get cache-hit output
-        run: 'echo "Cache hit >>>>>: ${{ steps.init.outputs.cache-hit }}"'
-      - name: Check
-        run: cargo clippy --all-features --all-targets -- -D warnings
+  #  # Get the output of the prepare composite action
+  #     - name: Get cache-hit output
+  #       run: 'echo "Cache hit >>>>>: ${{ steps.init.outputs.cache-hit }}"'
+  #     - name: Check
+  #       run: cargo clippy --all-features --all-targets -- -D warnings
 
-  # Run tests
-  test:
-    if: |
-      ${{ github.event.pull_request.draft == false && needs.changed_files.outputs.changed-tests-files == 'true' }}
-    permissions:
-      contents: read
-    needs: changed_files
-    runs-on: ubuntu-latest
-    steps:
-      # Checkout the repository
-      - name: Checkout Code
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
-      - name: Prepare
-        id: init
-        uses: ./.github/actions/prepare
-        with:
-          components: llvm-tools-preview
+  #  # Run tests
+  # test:
+  #   if: |
+  #     ${{ github.event.pull_request.draft == false && needs.changed_files.outputs.changed-tests-files == 'true' }}
+  #   permissions:
+  #     contents: read
+  #   needs: changed_files
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 20
+  #   steps:
+  #  # Checkout the repository
+  #     - name: Checkout Code
+  #       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
+  #     - name: Prepare
+  #       id: init
+  #       uses: ./.github/actions/prepare
+  #       with:
+  #         components: llvm-tools-preview
 
-      # Get the output of the prepare composite action
-      - name: Get cache-hit output
-        run: 'echo "Cache hit >>>>>: ${{ steps.init.outputs.cache-hit }}"'
-      - name: Install cargo hack
-        uses: taiki-e/install-action@cargo-hack
-      - name: Install cargo-llvm-cov
-        uses: taiki-e/install-action@cargo-llvm-cov
-      - name: Build
-        run: cargo test --no-run --locked
+  #  # Get the output of the prepare composite action
+  #     - name: Get cache-hit output
+  #       run: 'echo "Cache hit >>>>>: ${{ steps.init.outputs.cache-hit }}"'
+  #     - name: Install cargo hack
+  #       uses: taiki-e/install-action@cargo-hack
+  #     - name: Install cargo-llvm-cov
+  #       uses: taiki-e/install-action@cargo-llvm-cov
+  #     - name: Build
+  #       run: cargo test --no-run --locked
 
-      # Unit tests coverage
-      - name: Generate Unit Coverage Report
-        env:
-          LLVM_PROFILE_FILE: unit-%p-%m.profraw
-          RUSTFLAGS: -Cinstrument-coverage
-        run: RUST_TEST_THREADS=1 cargo hack llvm-cov --locked --lcov --output-path unit-lcov.info --lib
+  #  # Unit tests coverage
+  #     - name: Generate Unit Coverage Report
+  #       env:
+  #         LLVM_PROFILE_FILE: unit-%p-%m.profraw
+  #         RUSTFLAGS: -Cinstrument-coverage
+  #       run: RUST_TEST_THREADS=1 cargo hack llvm-cov --locked --lcov --output-path unit-lcov.info --lib
 
-      # Integration tests coverage
-      - name: Generate Integration Coverage Report
-        env:
-          LLVM_PROFILE_FILE: integration-%p-%m.profraw
-          RUSTFLAGS: -Cinstrument-coverage
-        run: RUST_TEST_THREADS=1 cargo hack llvm-cov --locked --lcov --output-path integration-lcov.info --test integration
-      - name: Generate Properties Coverage Report
-        env:
-          LLVM_PROFILE_FILE: properties-%p-%m.profraw
-          RUSTFLAGS: -Cinstrument-coverage
-        run: RUST_TEST_THREADS=1 cargo hack llvm-cov --locked --lcov --output-path properties-lcov.info --test properties
+  #  # Integration tests coverage
+  #     - name: Generate Integration Coverage Report
+  #       env:
+  #         LLVM_PROFILE_FILE: integration-%p-%m.profraw
+  #         RUSTFLAGS: -Cinstrument-coverage
+  #       run: RUST_TEST_THREADS=1 cargo hack llvm-cov --locked --lcov --output-path integration-lcov.info --test integration
+  #     - name: Generate Properties Coverage Report
+  #       env:
+  #         LLVM_PROFILE_FILE: properties-%p-%m.profraw
+  #         RUSTFLAGS: -Cinstrument-coverage
+  #       run: RUST_TEST_THREADS=1 cargo hack llvm-cov --locked --lcov --output-path properties-lcov.info --test properties
 
-      # Upload unit coverage
-      - name: Upload Unit Coverage to Codecov
-        uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574  # v5.4.0
-        with:
-          token: ${{ secrets.CODECOV_TOKEN }}
-          name: unit-coverage
-          files: unit-lcov.info
-          flags: unittests
-          fail_ci_if_error: false
+  #  # Upload unit coverage
+  #     - name: Upload Unit Coverage to Codecov
+  #       uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574  # v5.4.0
+  #       with:
+  #         token: ${{ secrets.CODECOV_TOKEN }}
+  #         name: unit-coverage
+  #         files: unit-lcov.info
+  #         flags: unittests
+  #         fail_ci_if_error: false
 
-      # Upload integration coverage
-      - name: Upload Integration Coverage to Codecov
-        uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574  # v5.4.0
-        with:
-          token: ${{ secrets.CODECOV_TOKEN }}
-          name: integration-coverage
-          files: integration-lcov.info
-          flags: integration
-          fail_ci_if_error: false
+  #  # Upload integration coverage
+  #     - name: Upload Integration Coverage to Codecov
+  #       uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574  # v5.4.0
+  #       with:
+  #         token: ${{ secrets.CODECOV_TOKEN }}
+  #         name: integration-coverage
+  #         files: integration-lcov.info
+  #         flags: integration
+  #         fail_ci_if_error: false
 
-      # Upload properties coverage
-      - name: Upload Properties Coverage to Codecov
-        uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574  # v5.4.0
-        with:
-          token: ${{ secrets.CODECOV_TOKEN }}
-          name: properties-coverage
-          files: properties-lcov.info
-          flags: properties
-          fail_ci_if_error: false
+  #  # Upload properties coverage
+  #     - name: Upload Properties Coverage to Codecov
+  #       uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574  # v5.4.0
+  #       with:
+  #         token: ${{ secrets.CODECOV_TOKEN }}
+  #         name: properties-coverage
+  #         files: properties-lcov.info
+  #         flags: properties
+  #         fail_ci_if_error: false
   docker-scan:
-    runs-on: ubuntu-22.04-oz-4core
-    needs: [changed_files, ci]
-    if: |
-      ${{ github.event.pull_request.draft == false && needs.changed_files.outputs.changed-docker-files == 'true' }}
+    runs-on: ubuntu-latest
+    timeout-minutes: 20
+   # needs: [changed_files, ci]
+    # if: |
+    #  ${{ github.event.pull_request.draft == false && needs.changed_files.outputs.changed-docker-files == 'true' }}
     steps:
       # Checkout the repository
       - name: Checkout Code
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
+      - name: Rust version
+        run: rustc --version
+      - name: Cargo version
+        run: cargo --version
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2  # v3.10.0
       - name: Build local container
