fix: Move json outputs to separate step

diff --git a/.github/workflows/release-please.yml b/.github/workflows/release-please.yml
--- a/.github/workflows/release-please.yml
+++ b/.github/workflows/release-please.yml
@@ -10,11 +10,13 @@ permissions:
   actions: read
   contents: write
   pull-requests: write
+  attestations: write
+  packages: write
 
 # run concurrency group for the workflow
-concurrency:
-  group: ${{ github.workflow }}-${{ github.ref }}
-  cancel-in-progress: false
+# concurrency:
+#   group: ${{ github.workflow }}-${{ github.ref }}
+#   cancel-in-progress: false
 
 jobs:
   release-please:
@@ -22,9 +24,12 @@ jobs:
     outputs:
       release_created: ${{ steps.release.outputs.releases_created }}
       pr_created: ${{ steps.release.outputs.prs_created }}
-      release_branch: ${{ fromJSON(steps.release.outputs.pr).headBranchName }}
+      release_branch: ${{ steps.get_release_branch.outputs.release_branch }}
       version: ${{ steps.release.outputs.version }}
       tag: ${{ steps.release.outputs.tag_name }}
+    env:
+      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+      SLACK_CHANNEL: '#oss-releases'
     steps:
       - name: Get github app token
         uses: actions/create-github-app-token@af35edadc00be37caa72ed9f3e6d5f7801bfdf09  # v1.11.7
@@ -32,6 +37,15 @@ jobs:
         with:
           app-id: ${{ vars.GH_APP_ID }}
           private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
+
+      - name: Slack notification
+        uses: act10ns/slack@44541246747a30eb3102d87f7a4cc5471b0ffb7d  # v2.1.0
+        with:
+          status: starting
+          steps: ${{ toJson(steps) }}
+          channel: ${{ env.SLACK_CHANNEL }}
+          message: Starting release please workflow for ${{ github.repository }}
+        if: always()
 
       - name: Checkout release branch
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
@@ -77,16 +91,34 @@ jobs:
           PR_NUMBER=${{ steps.get_pr.outputs.pr_number_output }}
           echo "Found merged PR number: $PR_NUMBER"
 
-          # Fetch PR details and extract labels
-          PR_LABELS=$(gh api --jq '.labels.[].name' /repos/OpenZeppelin/openzeppelin-monitor/pulls/$PR_NUMBER)
+          retries=3
+          wait=2
 
-          echo "PR labels: $PR_LABELS"
+          while [[ $retries -gt 0 ]]; do
+            # Fetch PR details and extract labels
+            PR_LABELS=$(gh api --jq '.labels.[].name' /repos/${{ github.repository }}/pulls/$PR_NUMBER)
 
-          if echo "$PR_LABELS" | grep -q "autorelease: pending"; then
-            echo "Label 'autorelease: pending' found. Unlocking conversation..."
-            gh pr unlock $PR_NUMBER
-          else
-            echo "Label 'autorelease: pending' not found. Skipping unlock."
+            if echo "$PR_LABELS" | grep -q "autorelease: pending"; then
+              echo "Label 'autorelease: pending' found. Attempting to unlock..."
+              gh pr unlock $PR_NUMBER
+              if [[ $? -eq 0 ]]; then
+                echo "PR unlocked successfully."
+                break
+              else
+                echo "Failed to unlock PR. Retrying in $wait seconds..."
+                sleep $wait
+                wait=$((wait * 2))
+                retries=$((retries - 1))
+              fi
+            else
+              echo "Label 'autorelease: pending' not found. Skipping unlock."
+              break
+            fi
+          done
+
+          if [[ $retries -eq 0 ]]; then
+            echo "Failed to unlock PR after multiple retries."
+            exit 1  # Fail the step if unlocking consistently fails
           fi
         env:
           GH_TOKEN: ${{ steps.gh-app-token.outputs.token }}
@@ -98,13 +130,29 @@ jobs:
         with:
           token: ${{ steps.gh-app-token.outputs.token }}
           target-branch: ${{ github.ref_name }}
-          config-file: .release-config.json
-          manifest-file: .release-manifest.json
+          config-file: .github/release-please/config.json
+          manifest-file: .github/release-please/manifest.json
 
+      - name: Get release branch name on release please prs
+        if: ${{ steps.release.outputs.releases_created == 'false' }}
+        id: get_release_branch
+        run: |
+          echo "release_branch=${{ fromJSON(steps.release.outputs.pr).headBranchName }}" >> $GITHUB_OUTPUT
+
+      - name: Slack notification success or failure
+        uses: act10ns/slack@44541246747a30eb3102d87f7a4cc5471b0ffb7d  # v2.1.0
+        with:
+          status: ${{ job.status }}
+          steps: ${{ toJson(steps) }}
+          channel: ${{ env.SLACK_CHANNEL }}
+          message: Release please flow ${{ job.status }}
+        if: always()
+
+  # Cargo lock update
   update-cargo-lockfile:
     runs-on: ubuntu-latest
     needs: release-please
-    if: ${{ needs.release-please.outputs.pr_created == 'true' }}
+    if: ${{ needs.release-please.outputs.release_created == 'false' }}
     steps:
       - name: Get github app token
         uses: actions/create-github-app-token@af35edadc00be37caa72ed9f3e6d5f7801bfdf09  # v1.11.7
@@ -158,31 +206,29 @@ jobs:
           files: |-
             Cargo.lock
 
+  # Trigger workflow to generate sbom
   release-sbom:
-    runs-on: ubuntu-latest
     needs: release-please
     if: ${{ needs.release-please.outputs.release_created == 'true' }}
-    steps:
-      - name: Get github app token
-        uses: actions/create-github-app-token@af35edadc00be37caa72ed9f3e6d5f7801bfdf09  # v1.11.7
-        id: gh-app-token
-        with:
-          app-id: ${{ vars.GH_APP_ID }}
-          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
+    uses: ./.github/workflows/release-sbom.yml
+    with:
+      tag: ${{ needs.release-please.outputs.tag }}
+    secrets: inherit
 
-      - name: Run SBOM
-        uses: anchore/sbom-action@f325610c9f50a54015d37c8d16cb3b0e2c8f4de0  # v0.18.0
-        with:
-          upload-artifact-retention: 7
-          upload-release-assets: false
-          github-token: ${{ steps.gh-app-token.outputs.token }}
-          output-file: openzeppelin-monitor-${{ needs.release-please.outputs.version
-            }}-spdx.json
-          artifact-name: openzeppelin-monitor-${{ needs.release-please.outputs.version
-            }}-spdx.json
+  # Trigger workflow to publish binaries
+  release-binaries:
+    if: ${{ needs.release-please.outputs.release_created == 'true' }}
+    needs: release-please
+    uses: ./.github/workflows/release-bins.yml
+    with:
+      tag: ${{ needs.release-please.outputs.tag }}
+    secrets: inherit
 
-      - name: Upload Release Artifact
-        env:
-          GH_TOKEN: ${{ steps.gh-app-token.outputs.token }}
-        run: gh release upload ${{ needs.release-please.outputs.tag }} ./openzeppelin-monitor-${{
-          needs.release-please.outputs.version }}-spdx.json
+  # Trigger workflow to publish docker images
+  release-docker:
+    if: ${{ needs.release-please.outputs.release_created == 'true' }}
+    needs: release-please
+    uses: ./.github/workflows/release-docker.yml
+    with:
+      tag: ${{ needs.release-please.outputs.tag }}
+    secrets: inherit
